baseURL = "https://mikeruth.me/"
languageCode = "en-us"
title = "Mike Ruth"
theme = "mikeruth"

[params]
  author = "Mike Ruth"

[menu]
  [[menu.main]]
    identifier = "building"
    name = "Building + Patents"
    url = "/building/"
    weight = 10
  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/writing/"
    weight = 20
  [[menu.main]]
    identifier = "speaking"
    name = "Speaking"
    url = "/speaking/"
    weight = 30
